### ISSUE TITLE
(idea) use terraform aws_ami to automatically fetch latest training image

### ISSUE THREAD

**Issue by vinyar** [jerryaldrichiii/garcon-de-chef-training#12]
https://www.terraform.io/docs/providers/aws/d/ami.html

It may be able to sort by time, so we may be able to work around inconsistent naming conventions.

**Comment by jerryaldrichiii** [comment]
Great find @vinyar. However, since the AMI ID is specified in the config file I do not want to hardcode logic into this project to select it. To me that should be handled out of band.

**Comment by jerryaldrichiii** [comment]
Closing now, but feel to reopen to chat.
