### ISSUE TITLE
Linux Essentials require 5 instances per student.

### ISSUE THREAD

**Issue by SteveDelFante** [jerryaldrichiii/garcon-de-chef-training#21]
Linux Essentials require 5 instances per student now...not 4.

Here is the context in Appendix Z.

3. Select Essentials - CentOS 6.7 - 7.0.0 (ami-d5d7ffae) from the list of options.
4.	Click Launch.  The "Step 2" page displays.
5.	Select the first Micro Instance from the list provided and click Next: Configure Instance Details at the bottom of the screen.  The "Step 3" page displays.
6.	Enter the Number of Instances.
**Note:  You will need **5** instances for each student enrolled in the class - and 5 for yourself. (One will be used for the Day 1 virtual workstation, one used as a load balancer, and 3 as web servers. The Day 1 virtual workstations can be stopped or terminated (to avoid confusion) after Day 1 is complete if you and your students agree to that.**

**Comment by SteveDelFante** [comment]
The above issue will be applicable after I release the new version of Linux Essentials (v.2.2.0), probably  tomorrow 8/25/17.

**Comment by jerryaldrichiii** [comment]
Fixed in PR #22.
