### ISSUE TITLE
Update Readme to delete class infra...

### ISSUE THREAD

**Issue by larryebaum** [jerryaldrichiii/garcon-de-chef-training#4]
Upon completion of class (or at whatever point you want to delete class VMs)
cd into `garcon-de-chef-training/output/<date>-<customer>-<class>` directory
Execute `terraform destroy`
Log into AWS to verify VMs and VPC are deleted.

**Comment by jerryaldrichiii** [comment]
Added a `Cleanup` section to the `README.md`

Thanks for the suggestion!
